    version: "3.9"

    # The base template for trade-executor live trading
    x-trade-executor: &default-trade-executor
      image: ghcr.io/tradingstrategy-ai/trade-executor:${TRADE_EXECUTOR_VERSION}
      # All live executors have internal exception recovery mechanism,
      # If trade executor stops it must be manually restarted.
      # However webhook server stays around and can still take commands
      # even if the trade executor loop has stopped.
      restart: "no"
      mem_swappiness: 0
      volumes:
        # Map the path from where we load the strategy Python modules
        - ./strategy:/usr/src/trade-executor/strategy
        # Save the strategy execution state in the local filesystem
        - ./state:/usr/src/trade-executor/state
        # Cache the dataset downloads in the local filesystem
        - ./cache:/usr/src/trade-executor/cache
        # Save the log files to the local file system
        - ./logs:/usr/src/trade-executor/logs

      # This is the default trade-executor command to
      # launch as a daemon mode.
      # There are several subcommands.
      command: start

    services:

      # This is your trade executor name
      hotwallet-polygon-eth-usdc-breakout:
        <<: *default-trade-executor
        container_name: hotwallet-polygon-eth-usdc-breakout
        platform: linux/x86_64  # Needed when running on macOS
        ports:  
          # Web API for frontend would be exposed in this port,
          # 
          - "127.0.0.1:19006:3456"
        env_file:
          - ~/secrets/enzyme-polygon-eth-usdc-final.env